[workspace]
members = [
  "background-script",
  "foreground-script",
  "options",
  "messages"
]

[patch.crates-io]
messages           = { path = "messages" }
web-extensions-sys = { path = "../../"   }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
