[package]
name = "background-script"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
gloo-console = "0.2.1"
wasm-bindgen = "0.2.81"
web-extensions-sys = "0.1.0"
